line-length = 120
fix = true

[lint]
select = ["ALL"]
ignore = [
    # General:
    "RET504", # Unnecessary assignment to `variable` before `return` statement
    "TRY003", # Avoid specifying long messages outside the exception class

    # Todos:
    "TD002",  # Missing author name
    "FIX002", # Line contains TODO, consider resolving the issue

    # Docstring:
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D401", # First line should be in imperative mood; try rephrasing
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the second line
    "B904", 
    "EM102",
    "EM101",
    "TRY301",
    "PTH123",
    "BLE001",
    "RUF010",
    "C901",
    "SIM115",
]
extend-safe-fixes = [
    "D400",  # First line should end with a period
    "EM102", # Exception must not use an f-string literal, assign to variable first
]

[lint.isort]
force-single-line = true
required-imports = ["from __future__ import annotations"]
known-first-party = ["."]
length-sort = true

[lint.per-file-ignores]
"*.ipynb" = ["ALL"]